name: Publish

on:
  release:
    types: [ created ]

jobs:
  pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          pip install wheel
          pip install -e .
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}


  docs:
    name: Build docs for Github Pages
    runs-on: ubuntu-latest
    env:
      MNI_DATAPATH: /opt/CIVET/dist/share
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # For pdoc to resolve the defined constants, these files need to exist
      - name: Download surface-extraction models
        uses: actions/checkout@v3
        with:
          path: surface-extraction
          repository: aces/surface-extraction
      - name: Copy data to MNI_DATAPATH
        run: |
          sudo mkdir -pv $MNI_DATAPATH/surface-extraction
          sudo cp -v surface-extraction/models/* $MNI_DATAPATH/surface-extraction

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Pip
        run: |
          pip install -e .
          pip install pdoc
      - name: Pdoc
        run:  pdoc --footer-text='Version ${{ github.ref_name }}' civet -o pdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: pdoc
