name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  local:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install -e .
          pip install pytest pytest_mock
      - run: pytest
        # Dummy variable.
        # Note to future self: if things stop working, try populating
        # MNI_DATAPATH with the expected real data such as
        # surface-extraction/white_model_320.obj
        env:
          MNI_DATAPATH: /usr/local/share
